name: aur builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/akac97/archlinux-builder:main
      options: "--privileged"
    steps:
      - name: whoami
        run: whoami
      - name: enable multi-core
        run: sudo echo "MAKEFLAGS=\"-j$(nproc)\"" >> /etc/makepkg.conf
      - name: install deps
        run: sudo pacman -S git git-lfs --noconfirm
      - name: git clone
        run: git clone https://aur.archlinux.org/librewolf.git
      - name: cd
        run: cd librewolf
      - name: makpkg
        run: makepkg --syncdeps --noconfirm
