name: aur builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/akac97/archlinux-builder:main
    steps:
      - name: whoami
        run: whoami
      - name: enable multi-core compilation
        run: sudo sh -c 'echo "MAKEFLAGS=\"-j$(nproc)\"" >> /etc/makepkg.conf'
      - name: install deps
        run: sudo pacman -S git git-lfs --noconfirm
      - name: build
        run: |
             cd /home/builder
             git clone https://aur.archlinux.org/yay.git
             cd yay
             makepkg -si --noconfirm
             ls
